version: '3.8'

services:
  react-app:
    build:
      context: ./pickingupsteam
      dockerfile: Dockerfile

    depends_on:
      - express-server
    env_file:
      - ./pickingupsteam/.env
    volumes:
      - ./react-app:/app  # Mount local react app
      - /app/node_modules 
    ports:
      - "${REACT_APP_PORT}:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true  # Enable auto reload
    command: npm start

  express-server:
    build:
      context: ./Server
      dockerfile: Dockerfile
    env_file:
      - ./Server/.env
    ports:
      - "${PORT}:8080"
    volumes:
      - ./Server:/app  # Mount local Express server
      - /app/node_modules
    command: npm run dev

    
